name: Increment Git Tag
description: Increments git tag based on provided version type

inputs:
  version-type:
    description: Provide version type [major, minor, patch]
    required: true
    default: pathc

outputs:
  new-version:
    description: Incremented version based on the input

runs:
  using: node20
  main: action/index.js